export const FETCH_CURRENT_UTC_TIME = 'FETCH_CURRENT_UTC_TIME';
export const FETCH_CURRENT_UTC_TIME_LOADING = 'FETCH_CURRENT_UTC_TIME_LOADING';
export const FETCH_CURRENT_UTC_TIME_SUCCESS = 'FETCH_CURRENT_UTC_TIME_SUCCESS';
export const FETCH_CURRENT_UTC_TIME_ERROR = 'FETCH_CURRENT_UTC_TIME_ERROR';